CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "skills" (
  "skill_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
  "application_id" int NOT NULL,
  "skill" varchar NOT NULL,
  "comfort_level" varchar NOT NULL
);

CREATE TABLE "applications" (
  "application_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
  "user_id" int NOT NULL,
  "contact_id" int,
  "employer" varchar NOT NULL,
  "employment_type" varchar NOT NULL,
  "application_status" varchar,
  "application_deadline" timestamp NOT NULL,
  "location" varchar,
  "url" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "contacts" (
  "contact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
  "application_id" int,
  "user_id" int NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar,
  "phone_number" varchar,
  "linkedin_url" varchar,
  "created_at" timestamp DEFAULT (now())
);

ALTER TABLE "skills" ADD FOREIGN KEY ("application_id") REFERENCES "applications" ("application_id");

ALTER TABLE "applications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "contacts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

CREATE TABLE "applications_contacts" (
  "applications_contact_id" int,
  "contacts_contact_id" int,
  PRIMARY KEY ("applications_contact_id", "contacts_contact_id")
);

ALTER TABLE "applications_contacts" ADD FOREIGN KEY ("applications_contact_id") REFERENCES "applications" ("application_id");

ALTER TABLE "applications_contacts" ADD FOREIGN KEY ("contacts_contact_id") REFERENCES "contacts" ("contact_id");

